// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineSurveyTool.Server.DAL.Models;

#nullable disable

namespace OnlineSurveyTool.Server.DAL.Models.Migrations
{
    [DbContext(typeof(OstDbContext))]
    partial class OstDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.Answer", b =>
                {
                    b.Property<int>("SurveyResultId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("QuestionId")
                        .HasColumnType("varchar(36)");

                    b.HasKey("SurveyResultId", "QuestionNumber");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Answer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("$ResultId")
                        .HasColumnType("int");

                    b.Property<string>("ChoiceOptionId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceOptionId");

                    b.HasIndex("$ResultId", "Number");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.ChoiceOption", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("CanBeSkipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Maximum")
                        .HasColumnType("double");

                    b.Property<double?>("Minimum")
                        .HasColumnType("double");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("SurveyId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.Survey", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("OpeningDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.SurveyResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SurveyId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.AnswerMultipleChoice", b =>
                {
                    b.HasBaseType("OnlineSurveyTool.Server.DAL.Models.Answer");

                    b.Property<int?>("ResultId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasIndex("ResultId");

                    b.HasDiscriminator().HasValue("AnswerMultipleChoice");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.AnswerNumerical", b =>
                {
                    b.HasBaseType("OnlineSurveyTool.Server.DAL.Models.Answer");

                    b.Property<double>("Answer")
                        .HasColumnType("double");

                    b.Property<int?>("ResultId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasIndex("ResultId");

                    b.ToTable("Answer", t =>
                        {
                            t.Property("ResultId")
                                .HasColumnName("AnswerNumerical_ResultId");
                        });

                    b.HasDiscriminator().HasValue("AnswerNumerical");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.AnswerSingleChoice", b =>
                {
                    b.HasBaseType("OnlineSurveyTool.Server.DAL.Models.Answer");

                    b.Property<string>("ChoiceOptionId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<int?>("ResultId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasIndex("ChoiceOptionId");

                    b.HasIndex("ResultId");

                    b.ToTable("Answer", t =>
                        {
                            t.Property("ResultId")
                                .HasColumnName("AnswerSingleChoice_ResultId");
                        });

                    b.HasDiscriminator().HasValue("AnswerSingleChoice");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.AnswerTextual", b =>
                {
                    b.HasBaseType("OnlineSurveyTool.Server.DAL.Models.Answer");

                    b.Property<int?>("ResultId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)");

                    b.HasIndex("ResultId");

                    b.ToTable("Answer", t =>
                        {
                            t.Property("ResultId")
                                .HasColumnName("AnswerTextual_ResultId");
                        });

                    b.HasDiscriminator().HasValue("AnswerTextual");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.Answer", b =>
                {
                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.AnswerOption", b =>
                {
                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.ChoiceOption", "ChoiceOption")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("ChoiceOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.AnswerMultipleChoice", "Answer")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("$ResultId", "Number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("ChoiceOption");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.ChoiceOption", b =>
                {
                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.Question", "Question")
                        .WithMany("ChoiceOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.Question", b =>
                {
                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.Survey", b =>
                {
                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.User", "Owner")
                        .WithMany("Surveys")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.SurveyResult", b =>
                {
                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.Survey", "Survey")
                        .WithMany("Results")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.AnswerMultipleChoice", b =>
                {
                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.SurveyResult", "Result")
                        .WithMany("MultipleChoiceAnswers")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.AnswerNumerical", b =>
                {
                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.SurveyResult", "Result")
                        .WithMany("NumericalAnswers")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.AnswerSingleChoice", b =>
                {
                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.ChoiceOption", "ChoiceOption")
                        .WithMany("Answers")
                        .HasForeignKey("ChoiceOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.SurveyResult", "Result")
                        .WithMany("SingleChoiceAnswers")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoiceOption");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.AnswerTextual", b =>
                {
                    b.HasOne("OnlineSurveyTool.Server.DAL.Models.SurveyResult", "Result")
                        .WithMany("TextualAnswers")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.ChoiceOption", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("Answers");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ChoiceOptions");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.Survey", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.SurveyResult", b =>
                {
                    b.Navigation("MultipleChoiceAnswers");

                    b.Navigation("NumericalAnswers");

                    b.Navigation("SingleChoiceAnswers");

                    b.Navigation("TextualAnswers");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.User", b =>
                {
                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("OnlineSurveyTool.Server.DAL.Models.AnswerMultipleChoice", b =>
                {
                    b.Navigation("AnswerOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
